### ISSUE TITLE
Feature request: Configurable limits

### ISSUE THREAD

**Issue by Impact123** [jehy/hass-dbstats#2]
Currently the limits are hard coded. For example these
https://github.com/jehy/hass-dbstats/blob/47f95ed020b67f3fc3b7f25fe1434078c04a96d2/backend/src/state/state.service.ts#L32
https://github.com/jehy/hass-dbstats/blob/47f95ed020b67f3fc3b7f25fe1434078c04a96d2/backend/src/statistic/statistic.service.ts#L26
It would be nice if these were configurable in some way.

**Comment by jehy** [comment]
Great idea. I felt something was off when hardcoded those :)
Gonna add it as addon options.

**Comment by Impact123** [comment]
I'm not using the addon though. I use the docker image. My thought was either environment variables similar to `DB_CONNECT_STRING` or just command line parameters/arguments. Whatever is easier to implement or re-use for both sides.

**Comment by jehy** [comment]
No problem, addon options are passed as environment variables :)

**Comment by Impact123** [comment]
I just got a notification about a new release and tested it. The limit works for all but `Number of rows in tables`, `Table size in MB` in the `Generic database stats` section and  `Shared attributes size, MB` in the `Attributes` section. You probably already know this but just to let you know.

**Comment by jehy** [comment]
> I just got a notification about a new release and tested it. The limit works for all but `Number of rows in tables`, `Table size in MB` in the `Generic database stats` section and `Shared attributes size, MB` in the `Attributes` section. You probably already know this but just to let you know.

Yeah, that's a release for this issue :)
Number of rows and table size is not limited. I suppose, that there are no more table tables to show.
Concerning `Shared attributes` - fixed it, should work in latest release (tagged as 0.3.14)

**Comment by Impact123** [comment]
Ah. That explains it. I did a very simple test by limiting to 5 and it showed the same amount as before.
I also noticed that some labels are half as many as there are "lines" but this is probably a topic for another issue.

**Comment by jehy** [comment]
> I also noticed that some labels are half as many as there are "lines" but this is probably a topic for another issue.

Yeah, you are welcome. My HA installation is relatively small, so I can't reproduce many issues by myself :)

**Comment by Impact123** [comment]
I might try to gather some information and create an issue for that the next few days.
For now I'm thankful you implemented this so thanks!
