### ISSUE TITLE
Bug report: Not every line in the chart has a label

### ISSUE THREAD

**Issue by Impact123** [jehy/hass-dbstats#3]
## Issue description
For some charts there are more lines than values. Or in other words, not every line has a label. See the `Count events by domain` here for an example
![image](https://github.com/jehy/hass-dbstats/assets/899193/1819ada9-01d1-4716-b29a-2f13e8ad94df)

This happens for
* Count events by domain
* Count states
* Shares attributes size, MB

This does not happen when `MAX_ROWS_IN_CHART` is set to `10` for example so this likely affects all charts, not just the ones I shared above. They just happen to not have as many labels.
It seems to break at exactly `MAX_ROWS_IN_CHART=29` in my case. Maybe it might help not to squeeze the values/labels but just extend the "outer layer".
I'd personally prefer that approach so the size/height of the labels stay the same as they become hard to read at, let's say `40`.

Please let me know if you need more information.

**Comment by jehy** [comment]
Oh. I funny bug.
You can point a mouse to the untitled line and it will show you it's name.
I'm gonna check what can be done with it.

**Comment by jehy** [comment]
Okay, looks like it's not so simple with chart.js. I made it a little better, but it looks like another chart library should be used. I'm not quite a frontend guy, so I will try it later when I have some spare time. PRs are welcome!

**Comment by jehy** [comment]
Hmm. That was easier then I expected. Please try version 0.3.16 with apex charts :)
Does it look better now?

**Comment by Impact123** [comment]
Unfortunately I'm not much of a frontend developer either. I'd hardly consider myself a developer at all.
Thanks for looking into this! I'll just list the improvements and the differences that I noticed.

## Positives
* The labels and values are now aligned and have the same count. The reported issue is fixed.
* Due to the different charting library the data can now be downloaded/exported

## Potentially unwanted/unintended differences
* The titles are now left-aligned rather than center as before. I don't really mind this
* Colors are a bit too harsh/dark but that's personal preference
* Text is smaller and harder to read
* Labels are cut off now.

Here's two pictures that show some of the mentioned points
![image](https://github.com/jehy/hass-dbstats/assets/899193/41dadb17-53fe-4656-a6ef-974fa4b10c07)
![image](https://github.com/jehy/hass-dbstats/assets/899193/25f60b6c-1234-4743-848a-0e473e51ea87)
---
* Big values don't have a separator anymore 
![image](https://github.com/jehy/hass-dbstats/assets/899193/87368377-9853-4411-967f-296c13e82c9f)
![image](https://github.com/jehy/hass-dbstats/assets/899193/5c0f6374-0018-4598-aee0-b647b8d01a2d)

That's all I noticed so far. No stress. This isn't (time) critical and not everything I listed has to be "fixed". I just wanted to be thorough with the report.

**Comment by jehy** [comment]
Thanks for the feedback!
It should look nicer now in 0.3.18 - I made font a little larger and only really long labels are trimmed now.

**Comment by jehy** [comment]
In 0.3.19 I was also able to fix bar height and revert to previous color schema from chart.js.

**Comment by Impact123** [comment]
Everything is enhanced but two things.
I censored my sensor names but you can see that almost all my labels are trimmed which wasn't the case before.
I think the label is more important than the value. Or rather the value is not useful without being able to see the label.
![oldshortterm](https://github.com/jehy/hass-dbstats/assets/899193/6b11e599-74cd-472b-b051-9cb7943c6baf)
![newshortterm](https://github.com/jehy/hass-dbstats/assets/899193/ce8e0355-b4d1-4436-8220-6972683cb378)

The longest label there was `56` characters. I checked my database and my longest entity name at the moment is `62` characters.
I don't think that's a lot lot for a sensor name. `80-100` might be a good value.

The separator in the bottom is not all that important to me but was useful for some charts
**Old**
![image](https://github.com/jehy/hass-dbstats/assets/899193/cd7b5fc5-9263-482b-9d87-f90aa0deb6e1)
**New**
![image](https://github.com/jehy/hass-dbstats/assets/899193/67f23b1c-a579-4009-b9ec-e415006cc644)

**Comment by jehy** [comment]
Makes sense. Try 3.20 :)

**Comment by Impact123** [comment]
Everything seems to work as expected. Awesome. Thank you very much!
I noticed some differences in the separator. Previously it was a `,` and now it's mostly a `.`
I saw the
```js
toLocaleString('en-us')
```
 in the diff. It might make sense to remove the `'en-us'` (or exchange it with the browser's locale) to make it adhere to the user's own locale.

There is also some inconsistency with small numbers.
**Comma**
![image](https://github.com/jehy/hass-dbstats/assets/899193/95133e93-2026-4450-a145-8235f40ea416)
**Dot**
![image](https://github.com/jehy/hass-dbstats/assets/899193/29135c97-a826-448c-8f03-e64623e6b4eb)

 I consider this issue fixed. You have my gratitude.
